TBC_MINING_RECIPES = {

[2575] = {
    spellID      = 2575,
    name         = "Mining",
    requiredSkill = 9999,
    resultItemID = nil,
    recipeItemID = nil,
    materials    = nil,
    resultIconID = nil,
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Belil", "Brek Stonehoof", "Brock Stoneseeker", "Brom Killian", "Dank Drizzlecut", "Dulvi", "Gelman Stonehand", "Geofram Bouldertoe", "Hurnak Grimmord", "Johan Focht", "Krugosh", "Krunn", "Kurdram Stonehammer", "Makaru", "Matt Johnson", "Muaat", "Pikkle", "Prospector Nachlan", "Yarr Hammerstone"},
},

[2576] = {
    spellID      = 2576,
    name         = "Mining",
    requiredSkill = 50,
    resultItemID = nil,
    recipeItemID = nil,
    materials    = nil,
    resultIconID = nil,
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Belil", "Brek Stonehoof", "Brock Stoneseeker", "Brom Killian", "Dank Drizzlecut", "Dulvi", "Gelman Stonehand", "Geofram Bouldertoe", "Hurnak Grimmord", "Johan Focht", "Krugosh", "Krunn", "Kurdram Stonehammer", "Makaru", "Matt Johnson", "Muaat", "Pikkle", "Prospector Nachlan", "Yarr Hammerstone"},
},

[2580] = {
    spellID      = 2580,
    name         = "Find Minerals",
    requiredSkill = 9999,
    resultItemID = nil,
    recipeItemID = nil,
    materials    = nil,
    resultIconID = nil,
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[2656] = {
    spellID      = 2656,
    name         = "Smelting",
    requiredSkill = 9999,
    resultItemID = nil,
    recipeItemID = nil,
    materials    = nil,
    resultIconID = nil,
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[2657] = {
    spellID      = 2657,
    name         = "Smelt Copper",
    requiredSkill = 25,
    resultItemID = 2840,
    recipeItemID = nil,
    materials    = {{ itemID = 2770, quantity = 1 }},
    resultIconID = "inv_ingot_02",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[2658] = {
    spellID      = 2658,
    name         = "Smelt Silver",
    requiredSkill = 75,
    resultItemID = 2842,
    recipeItemID = nil,
    materials    = {{ itemID = 2775, quantity = 1 }},
    resultIconID = "inv_ingot_01",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Belil", "Brek Stonehoof", "Brock Stoneseeker", "Brom Killian", "Dank Drizzlecut", "Dulvi", "Gelman Stonehand", "Geofram Bouldertoe", "Hurnak Grimmord", "Johan Focht", "Krugosh", "Krunn", "Kurdram Stonehammer", "Makaru", "Matt Johnson", "Muaat", "Pikkle", "Prospector Nachlan", "Yarr Hammerstone"},
},

[2659] = {
    spellID      = 2659,
    name         = "Smelt Bronze",
    requiredSkill = 65,
    resultItemID = 2841,
    recipeItemID = nil,
    materials    = {{ itemID = 2840, quantity = 1 }, { itemID = 3576, quantity = 1 }},
    resultIconID = "inv_ingot_bronze",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Belil", "Brek Stonehoof", "Brock Stoneseeker", "Brom Killian", "Dank Drizzlecut", "Dulvi", "Gelman Stonehand", "Geofram Bouldertoe", "Hurnak Grimmord", "Johan Focht", "Krugosh", "Krunn", "Kurdram Stonehammer", "Makaru", "Matt Johnson", "Muaat", "Pikkle", "Prospector Nachlan", "Yarr Hammerstone"},
},

[3304] = {
    spellID      = 3304,
    name         = "Smelt Tin",
    requiredSkill = 65,
    resultItemID = 3576,
    recipeItemID = nil,
    materials    = {{ itemID = 2771, quantity = 1 }},
    resultIconID = "inv_ingot_05",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Belil", "Brek Stonehoof", "Brock Stoneseeker", "Brom Killian", "Dank Drizzlecut", "Dulvi", "Gelman Stonehand", "Geofram Bouldertoe", "Hurnak Grimmord", "Johan Focht", "Krugosh", "Krunn", "Kurdram Stonehammer", "Makaru", "Matt Johnson", "Muaat", "Pikkle", "Prospector Nachlan", "Yarr Hammerstone"},
},

[3307] = {
    spellID      = 3307,
    name         = "Smelt Iron",
    requiredSkill = 125,
    resultItemID = 3575,
    recipeItemID = nil,
    materials    = {{ itemID = 2772, quantity = 1 }},
    resultIconID = "inv_ingot_iron",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Belil", "Brek Stonehoof", "Brock Stoneseeker", "Brom Killian", "Dank Drizzlecut", "Dulvi", "Gelman Stonehand", "Geofram Bouldertoe", "Hurnak Grimmord", "Johan Focht", "Krugosh", "Krunn", "Kurdram Stonehammer", "Makaru", "Matt Johnson", "Muaat", "Pikkle", "Prospector Nachlan", "Yarr Hammerstone"},
},

[3308] = {
    spellID      = 3308,
    name         = "Smelt Gold",
    requiredSkill = 155,
    resultItemID = 3577,
    recipeItemID = nil,
    materials    = {{ itemID = 2776, quantity = 1 }},
    resultIconID = "inv_ingot_03",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Belil", "Brek Stonehoof", "Brock Stoneseeker", "Brom Killian", "Dank Drizzlecut", "Dulvi", "Gelman Stonehand", "Geofram Bouldertoe", "Hurnak Grimmord", "Johan Focht", "Krugosh", "Krunn", "Kurdram Stonehammer", "Makaru", "Matt Johnson", "Muaat", "Pikkle", "Prospector Nachlan", "Yarr Hammerstone"},
},

[3564] = {
    spellID      = 3564,
    name         = "Mining",
    requiredSkill = 125,
    resultItemID = nil,
    recipeItemID = nil,
    materials    = nil,
    resultIconID = nil,
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Belil", "Brek Stonehoof", "Brock Stoneseeker", "Brom Killian", "Dank Drizzlecut", "Dulvi", "Gelman Stonehand", "Geofram Bouldertoe", "Hurnak Grimmord", "Johan Focht", "Krugosh", "Krunn", "Kurdram Stonehammer", "Makaru", "Matt Johnson", "Muaat", "Pikkle", "Prospector Nachlan", "Yarr Hammerstone"},
},

[3569] = {
    spellID      = 3569,
    name         = "Smelt Steel",
    requiredSkill = 165,
    resultItemID = 3859,
    recipeItemID = nil,
    materials    = {{ itemID = 3575, quantity = 1 }, { itemID = 3857, quantity = 1 }},
    resultIconID = "inv_ingot_steel",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Belil", "Brek Stonehoof", "Brock Stoneseeker", "Brom Killian", "Dank Drizzlecut", "Dulvi", "Gelman Stonehand", "Geofram Bouldertoe", "Hurnak Grimmord", "Johan Focht", "Krugosh", "Krunn", "Kurdram Stonehammer", "Makaru", "Matt Johnson", "Muaat", "Pikkle", "Prospector Nachlan", "Yarr Hammerstone"},
},

[10097] = {
    spellID      = 10097,
    name         = "Smelt Mithril",
    requiredSkill = 175,
    resultItemID = 3860,
    recipeItemID = nil,
    materials    = {{ itemID = 3858, quantity = 1 }},
    resultIconID = "inv_ingot_06",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Belil", "Brek Stonehoof", "Brock Stoneseeker", "Brom Killian", "Dank Drizzlecut", "Dulvi", "Gelman Stonehand", "Geofram Bouldertoe", "Hurnak Grimmord", "Johan Focht", "Krugosh", "Krunn", "Kurdram Stonehammer", "Makaru", "Matt Johnson", "Muaat", "Pikkle", "Prospector Nachlan", "Yarr Hammerstone"},
},

[10098] = {
    spellID      = 10098,
    name         = "Smelt Truesilver",
    requiredSkill = 230,
    resultItemID = 6037,
    recipeItemID = nil,
    materials    = {{ itemID = 7911, quantity = 1 }},
    resultIconID = "inv_ingot_08",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Belil", "Brek Stonehoof", "Brock Stoneseeker", "Brom Killian", "Dank Drizzlecut", "Dulvi", "Gelman Stonehand", "Geofram Bouldertoe", "Hurnak Grimmord", "Johan Focht", "Krugosh", "Krunn", "Kurdram Stonehammer", "Makaru", "Matt Johnson", "Muaat", "Pikkle", "Prospector Nachlan", "Yarr Hammerstone"},
},

[10248] = {
    spellID      = 10248,
    name         = "Mining",
    requiredSkill = 200,
    resultItemID = nil,
    recipeItemID = nil,
    materials    = nil,
    resultIconID = nil,
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Belil", "Brek Stonehoof", "Brock Stoneseeker", "Brom Killian", "Dank Drizzlecut", "Dulvi", "Gelman Stonehand", "Geofram Bouldertoe", "Hurnak Grimmord", "Johan Focht", "Krugosh", "Krunn", "Kurdram Stonehammer", "Makaru", "Matt Johnson", "Muaat", "Pikkle", "Prospector Nachlan", "Yarr Hammerstone"},
},

[14891] = {
    spellID      = 14891,
    name         = "Smelt Dark Iron",
    requiredSkill = 300,
    resultItemID = 11371,
    recipeItemID = nil,
    materials    = {{ itemID = 11370, quantity = 8 }},
    resultIconID = "inv_ingot_mithril",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[16153] = {
    spellID      = 16153,
    name         = "Smelt Thorium",
    requiredSkill = 250,
    resultItemID = 12359,
    recipeItemID = nil,
    materials    = {{ itemID = 10620, quantity = 1 }},
    resultIconID = "inv_ingot_07",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Belil", "Brek Stonehoof", "Brock Stoneseeker", "Brom Killian", "Dank Drizzlecut", "Dulvi", "Gelman Stonehand", "Geofram Bouldertoe", "Hurnak Grimmord", "Johan Focht", "Krugosh", "Krunn", "Kurdram Stonehammer", "Makaru", "Matt Johnson", "Muaat", "Pikkle", "Prospector Nachlan", "Yarr Hammerstone"},
},

[22967] = {
    spellID      = 22967,
    name         = "Smelt Elementium",
    requiredSkill = 350,
    resultItemID = 17771,
    recipeItemID = nil,
    materials    = {{ itemID = 18562, quantity = 1 }, { itemID = 12360, quantity = 10 }, { itemID = 17010, quantity = 1 }, { itemID = 18567, quantity = 3 }},
    resultIconID = "inv_ingot_thorium",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[29354] = {
    spellID      = 29354,
    name         = "Mining",
    requiredSkill = 275,
    resultItemID = nil,
    recipeItemID = nil,
    materials    = nil,
    resultIconID = nil,
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Hurnak Grimmord", "Krugosh"},
},

[29356] = {
    spellID      = 29356,
    name         = "Smelt Fel Iron",
    requiredSkill = 300,
    resultItemID = 23445,
    recipeItemID = nil,
    materials    = {{ itemID = 23424, quantity = 2 }},
    resultIconID = nil,
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Hurnak Grimmord", "Krugosh"},
},

[29358] = {
    spellID      = 29358,
    name         = "Smelt Adamantite",
    requiredSkill = 325,
    resultItemID = 23446,
    recipeItemID = nil,
    materials    = {{ itemID = 23425, quantity = 2 }},
    resultIconID = "inv_ingot_10",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Hurnak Grimmord", "Krugosh"},
},

[29359] = {
    spellID      = 29359,
    name         = "Smelt Eternium",
    requiredSkill = 350,
    resultItemID = 23447,
    recipeItemID = nil,
    materials    = {{ itemID = 23427, quantity = 2 }},
    resultIconID = nil,
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Hurnak Grimmord", "Krugosh"},
},

[29360] = {
    spellID      = 29360,
    name         = "Smelt Felsteel",
    requiredSkill = 350,
    resultItemID = 23448,
    recipeItemID = nil,
    materials    = {{ itemID = 23445, quantity = 3 }, { itemID = 23447, quantity = 2 }},
    resultIconID = "inv_ingot_felsteel",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Hurnak Grimmord", "Krugosh"},
},

[29361] = {
    spellID      = 29361,
    name         = "Smelt Khorium",
    requiredSkill = 375,
    resultItemID = 23449,
    recipeItemID = nil,
    materials    = {{ itemID = 23426, quantity = 2 }},
    resultIconID = "inv_ingot_09",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Hurnak Grimmord", "Krugosh"},
},

[29686] = {
    spellID      = 29686,
    name         = "Smelt Hardened Adamantite",
    requiredSkill = 375,
    resultItemID = 23573,
    recipeItemID = nil,
    materials    = {{ itemID = 23446, quantity = 10 }},
    resultIconID = "inv_ingot_adamantite",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Hurnak Grimmord", "Krugosh"},
},

[35750] = {
    spellID      = 35750,
    name         = "Earth Shatter",
    requiredSkill = 300,
    resultItemID = 22573,
    recipeItemID = nil,
    materials    = {{ itemID = 22452, quantity = 1 }},
    resultIconID = "inv_elemental_mote_earth01",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Hurnak Grimmord", "Krugosh"},
},

[35751] = {
    spellID      = 35751,
    name         = "Fire Sunder",
    requiredSkill = 300,
    resultItemID = 22574,
    recipeItemID = nil,
    materials    = {{ itemID = 21884, quantity = 1 }},
    resultIconID = "inv_elemental_mote_fire01",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Hurnak Grimmord", "Krugosh"},
},

[46353] = {
    spellID      = 46353,
    name         = "Smelt Hardened Khorium",
    requiredSkill = 375,
    resultItemID = 35128,
    recipeItemID = 35273,
    materials    = {{ itemID = 23449, quantity = 3 }, { itemID = 23573, quantity = 1 }},
    resultIconID = "inv_ingot_thorium",
    recipeIconID = "inv_misc_book_08",
    source       = "vendor",
    sourceDetail = nil,
},

}
