TBC_ALCHEMY_RECIPES = {

[2259] = {
    spellID      = 2259,
    name         = "Alchemy",
    requiredSkill = 9999,
    resultItemID = nil,
    recipeItemID = nil,
    materials    = nil,
    resultIconID = nil,
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Doctor Martin Felben", "Ghak Healtouch", "Jaxin Chong", "Kray", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Milla Fairancora", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Tel'Athir", "Vosur Brakthel", "Whuut", "Yelmak"},
},

[2329] = {
    spellID      = 2329,
    name         = "Elixir of Lion's Strength",
    requiredSkill = 1,
    resultItemID = 2454,
    recipeItemID = nil,
    materials    = {{ itemID = 2449, quantity = 1 }, { itemID = 765, quantity = 1 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_56",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[2330] = {
    spellID      = 2330,
    name         = "Minor Healing Potion",
    requiredSkill = 1,
    resultItemID = 118,
    recipeItemID = nil,
    materials    = {{ itemID = 2447, quantity = 1 }, { itemID = 765, quantity = 1 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_49",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[2331] = {
    spellID      = 2331,
    name         = "Minor Mana Potion",
    requiredSkill = 25,
    resultItemID = 2455,
    recipeItemID = nil,
    materials    = {{ itemID = 785, quantity = 1 }, { itemID = 765, quantity = 1 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_70",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Doctor Martin Felben", "Ghak Healtouch", "Jaxin Chong", "Kray", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Milla Fairancora", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Tel'Athir", "Vosur Brakthel", "Whuut", "Yelmak"},
},

[2332] = {
    spellID      = 2332,
    name         = "Minor Rejuvenation Potion",
    requiredSkill = 40,
    resultItemID = 2456,
    recipeItemID = nil,
    materials    = {{ itemID = 785, quantity = 2 }, { itemID = 2447, quantity = 1 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_02",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Doctor Martin Felben", "Ghak Healtouch", "Jaxin Chong", "Kray", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Milla Fairancora", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Tel'Athir", "Vosur Brakthel", "Whuut", "Yelmak"},
},

[2333] = {
    spellID      = 2333,
    name         = "Elixir of Lesser Agility",
    requiredSkill = 140,
    resultItemID = 3390,
    recipeItemID = 3396,
    materials    = {{ itemID = 3355, quantity = 1 }, { itemID = 2452, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_92",
    recipeIconID = "inv_scroll_03",
    source       = "vendor",
    sourceDetail = nil,
},

[2334] = {
    spellID      = 2334,
    name         = "Elixir of Minor Fortitude",
    requiredSkill = 50,
    resultItemID = 2458,
    recipeItemID = nil,
    materials    = {{ itemID = 2449, quantity = 2 }, { itemID = 2447, quantity = 1 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_42",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Doctor Martin Felben", "Ghak Healtouch", "Jaxin Chong", "Kray", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Milla Fairancora", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Tel'Athir", "Vosur Brakthel", "Whuut", "Yelmak"},
},

[2335] = {
    spellID      = 2335,
    name         = "Swiftness Potion",
    requiredSkill = 60,
    resultItemID = 2459,
    recipeItemID = 2555,
    materials    = {{ itemID = 2452, quantity = 1 }, { itemID = 2450, quantity = 1 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_95",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[2337] = {
    spellID      = 2337,
    name         = "Lesser Healing Potion",
    requiredSkill = 55,
    resultItemID = 858,
    recipeItemID = nil,
    materials    = {{ itemID = 118, quantity = 1 }, { itemID = 2450, quantity = 1 }},
    resultIconID = "inv_potion_50",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Doctor Martin Felben", "Ghak Healtouch", "Jaxin Chong", "Kray", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Milla Fairancora", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Tel'Athir", "Vosur Brakthel", "Whuut", "Yelmak"},
},

[3101] = {
    spellID      = 3101,
    name         = "Alchemy",
    requiredSkill = 50,
    resultItemID = nil,
    recipeItemID = nil,
    materials    = nil,
    resultIconID = nil,
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Yelmak"},
},

[3170] = {
    spellID      = 3170,
    name         = "Weak Troll's Blood Potion",
    requiredSkill = 15,
    resultItemID = 3382,
    recipeItemID = nil,
    materials    = {{ itemID = 2447, quantity = 1 }, { itemID = 2449, quantity = 2 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_77",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Doctor Martin Felben", "Ghak Healtouch", "Jaxin Chong", "Kray", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Milla Fairancora", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Tel'Athir", "Vosur Brakthel", "Whuut", "Yelmak"},
},

[3171] = {
    spellID      = 3171,
    name         = "Elixir of Wisdom",
    requiredSkill = 90,
    resultItemID = 3383,
    recipeItemID = nil,
    materials    = {{ itemID = 785, quantity = 1 }, { itemID = 2450, quantity = 2 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_06",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Yelmak"},
},

[3172] = {
    spellID      = 3172,
    name         = "Minor Magic Resistance Potion",
    requiredSkill = 110,
    resultItemID = 3384,
    recipeItemID = 3393,
    materials    = {{ itemID = 785, quantity = 3 }, { itemID = 3355, quantity = 1 }, { itemID = 3371, quantity = 1 }},
    resultIconID = nil,
    recipeIconID = nil,
    source       = "vendor",
    sourceDetail = nil,
},

[3173] = {
    spellID      = 3173,
    name         = "Lesser Mana Potion",
    requiredSkill = 120,
    resultItemID = 3385,
    recipeItemID = nil,
    materials    = {{ itemID = 785, quantity = 1 }, { itemID = 3820, quantity = 1 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_71",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Yelmak"},
},

[3174] = {
    spellID      = 3174,
    name         = "Potion of Curing",
    requiredSkill = 120,
    resultItemID = 3386,
    recipeItemID = 3394,
    materials    = {{ itemID = 1288, quantity = 1 }, { itemID = 2453, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_12",
    recipeIconID = "inv_scroll_03",
    source       = "vendor",
    sourceDetail = nil,
},

[3175] = {
    spellID      = 3175,
    name         = "Limited Invulnerability Potion",
    requiredSkill = 250,
    resultItemID = 3387,
    recipeItemID = 3395,
    materials    = {{ itemID = 8839, quantity = 2 }, { itemID = 8845, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_62",
    recipeIconID = "inv_scroll_03",
    source       = "vendor",
    sourceDetail = nil,
},

[3176] = {
    spellID      = 3176,
    name         = "Strong Troll's Blood Potion",
    requiredSkill = 125,
    resultItemID = 3388,
    recipeItemID = nil,
    materials    = {{ itemID = 2453, quantity = 2 }, { itemID = 2450, quantity = 2 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_78",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Yelmak"},
},

[3177] = {
    spellID      = 3177,
    name         = "Elixir of Defense",
    requiredSkill = 130,
    resultItemID = 3389,
    recipeItemID = nil,
    materials    = {{ itemID = 3355, quantity = 1 }, { itemID = 3820, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_64",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Yelmak"},
},

[3188] = {
    spellID      = 3188,
    name         = "Elixir of Ogre's Strength",
    requiredSkill = 150,
    resultItemID = 3391,
    recipeItemID = 6211,
    materials    = {{ itemID = 2449, quantity = 1 }, { itemID = 3356, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_57",
    recipeIconID = "inv_scroll_03",
    source       = "vendor",
    sourceDetail = nil,
},

[3230] = {
    spellID      = 3230,
    name         = "Elixir of Minor Agility",
    requiredSkill = 50,
    resultItemID = 2457,
    recipeItemID = 2553,
    materials    = {{ itemID = 2452, quantity = 1 }, { itemID = 765, quantity = 1 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_91",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[3447] = {
    spellID      = 3447,
    name         = "Healing Potion",
    requiredSkill = 110,
    resultItemID = 929,
    recipeItemID = nil,
    materials    = {{ itemID = 2453, quantity = 1 }, { itemID = 2450, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_51",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Yelmak"},
},

[3448] = {
    spellID      = 3448,
    name         = "Lesser Invisibility Potion",
    requiredSkill = 165,
    resultItemID = 3823,
    recipeItemID = nil,
    materials    = {{ itemID = 3818, quantity = 1 }, { itemID = 3355, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_18",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[3449] = {
    spellID      = 3449,
    name         = "Shadow Oil",
    requiredSkill = 165,
    resultItemID = 3824,
    recipeItemID = 6068,
    materials    = {{ itemID = 3818, quantity = 4 }, { itemID = 3369, quantity = 4 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_23",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[3450] = {
    spellID      = 3450,
    name         = "Elixir of Fortitude",
    requiredSkill = 175,
    resultItemID = 3825,
    recipeItemID = 3830,
    materials    = {{ itemID = 3355, quantity = 1 }, { itemID = 3821, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_43",
    recipeIconID = "inv_scroll_03",
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[3451] = {
    spellID      = 3451,
    name         = "Mighty Troll's Blood Potion",
    requiredSkill = 180,
    resultItemID = 3826,
    recipeItemID = 3831,
    materials    = {{ itemID = 3357, quantity = 1 }, { itemID = 2453, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_79",
    recipeIconID = "inv_scroll_03",
    source       = "vendor",
    sourceDetail = nil,
},

[3452] = {
    spellID      = 3452,
    name         = "Mana Potion",
    requiredSkill = 160,
    resultItemID = 3827,
    recipeItemID = nil,
    materials    = {{ itemID = 3820, quantity = 1 }, { itemID = 3356, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_72",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[3453] = {
    spellID      = 3453,
    name         = "Elixir of Detect Lesser Invisibility",
    requiredSkill = 195,
    resultItemID = 3828,
    recipeItemID = 3832,
    materials    = {{ itemID = 3358, quantity = 1 }, { itemID = 3818, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_01",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[3454] = {
    spellID      = 3454,
    name         = "Frost Oil",
    requiredSkill = 200,
    resultItemID = 3829,
    recipeItemID = 14634,
    materials    = {{ itemID = 3358, quantity = 4 }, { itemID = 3819, quantity = 2 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_20",
    recipeIconID = "inv_scroll_06",
    source       = "drop",
    sourceDetail = nil,
},

[3464] = {
    spellID      = 3464,
    name         = "Alchemy",
    requiredSkill = 125,
    resultItemID = nil,
    recipeItemID = nil,
    materials    = nil,
    resultIconID = nil,
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[4508] = {
    spellID      = 4508,
    name         = "Discolored Healing Potion",
    requiredSkill = 50,
    resultItemID = 4596,
    recipeItemID = nil,
    materials    = {{ itemID = 3164, quantity = 1 }, { itemID = 2447, quantity = 1 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_35",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[4942] = {
    spellID      = 4942,
    name         = "Lesser Stoneshield Potion",
    requiredSkill = 215,
    resultItemID = 4623,
    recipeItemID = nil,
    materials    = {{ itemID = 3858, quantity = 1 }, { itemID = 3821, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_67",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[6617] = {
    spellID      = 6617,
    name         = "Rage Potion",
    requiredSkill = 60,
    resultItemID = 5631,
    recipeItemID = 5640,
    materials    = {{ itemID = 5635, quantity = 2 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_24",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[6618] = {
    spellID      = 6618,
    name         = "Great Rage Potion",
    requiredSkill = 175,
    resultItemID = 5633,
    recipeItemID = 5643,
    materials    = {{ itemID = 5637, quantity = 1 }, { itemID = 3356, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_21",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[6624] = {
    spellID      = 6624,
    name         = "Free Action Potion",
    requiredSkill = 150,
    resultItemID = 5634,
    recipeItemID = 5642,
    materials    = {{ itemID = 6370, quantity = 2 }, { itemID = 3820, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_04",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[7179] = {
    spellID      = 7179,
    name         = "Elixir of Water Breathing",
    requiredSkill = 90,
    resultItemID = 5996,
    recipeItemID = nil,
    materials    = {{ itemID = 3820, quantity = 1 }, { itemID = 6370, quantity = 2 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_17",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Yelmak"},
},

[7181] = {
    spellID      = 7181,
    name         = "Greater Healing Potion",
    requiredSkill = 155,
    resultItemID = 1710,
    recipeItemID = nil,
    materials    = {{ itemID = 3357, quantity = 1 }, { itemID = 3356, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_52",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[7183] = {
    spellID      = 7183,
    name         = "Elixir of Minor Defense",
    requiredSkill = 1,
    resultItemID = 5997,
    recipeItemID = nil,
    materials    = {{ itemID = 765, quantity = 2 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_63",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[7255] = {
    spellID      = 7255,
    name         = "Holy Protection Potion",
    requiredSkill = 100,
    resultItemID = 6051,
    recipeItemID = 6053,
    materials    = {{ itemID = 2453, quantity = 1 }, { itemID = 2452, quantity = 1 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_09",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[7256] = {
    spellID      = 7256,
    name         = "Shadow Protection Potion",
    requiredSkill = 135,
    resultItemID = 6048,
    recipeItemID = 6054,
    materials    = {{ itemID = 3369, quantity = 1 }, { itemID = 3356, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_44",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[7257] = {
    spellID      = 7257,
    name         = "Fire Protection Potion",
    requiredSkill = 165,
    resultItemID = 6049,
    recipeItemID = 6055,
    materials    = {{ itemID = 4402, quantity = 1 }, { itemID = 6371, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_16",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[7258] = {
    spellID      = 7258,
    name         = "Frost Protection Potion",
    requiredSkill = 190,
    resultItemID = 6050,
    recipeItemID = 6056,
    materials    = {{ itemID = 3819, quantity = 1 }, { itemID = 3821, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_13",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[7259] = {
    spellID      = 7259,
    name         = "Nature Protection Potion",
    requiredSkill = 190,
    resultItemID = 6052,
    recipeItemID = 6057,
    materials    = {{ itemID = 3357, quantity = 1 }, { itemID = 3820, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_06",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[7836] = {
    spellID      = 7836,
    name         = "Blackmouth Oil",
    requiredSkill = 80,
    resultItemID = 6370,
    recipeItemID = nil,
    materials    = {{ itemID = 6358, quantity = 2 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_drink_12",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Yelmak"},
},

[7837] = {
    spellID      = 7837,
    name         = "Fire Oil",
    requiredSkill = 130,
    resultItemID = 6371,
    recipeItemID = nil,
    materials    = {{ itemID = 6359, quantity = 2 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_38",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Yelmak"},
},

[7841] = {
    spellID      = 7841,
    name         = "Swim Speed Potion",
    requiredSkill = 100,
    resultItemID = 6372,
    recipeItemID = nil,
    materials    = {{ itemID = 2452, quantity = 1 }, { itemID = 6370, quantity = 1 }, { itemID = 3371, quantity = 1 }},
    resultIconID = "inv_potion_13",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Yelmak"},
},

[7845] = {
    spellID      = 7845,
    name         = "Elixir of Firepower",
    requiredSkill = 140,
    resultItemID = 6373,
    recipeItemID = nil,
    materials    = {{ itemID = 6371, quantity = 2 }, { itemID = 3356, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_33",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Doctor Marsh", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Sylvanna Forestmoon", "Tally Berryfizz", "Yelmak"},
},

[8240] = {
    spellID      = 8240,
    name         = "Elixir of Giant Growth",
    requiredSkill = 90,
    resultItemID = 6662,
    recipeItemID = 6663,
    materials    = {{ itemID = 6522, quantity = 1 }, { itemID = 2449, quantity = 1 }, { itemID = 3371, quantity = 1 }},
    resultIconID = nil,
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[11448] = {
    spellID      = 11448,
    name         = "Greater Mana Potion",
    requiredSkill = 205,
    resultItemID = 6149,
    recipeItemID = nil,
    materials    = {{ itemID = 3358, quantity = 1 }, { itemID = 3821, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_73",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[11449] = {
    spellID      = 11449,
    name         = "Elixir of Agility",
    requiredSkill = 185,
    resultItemID = 8949,
    recipeItemID = nil,
    materials    = {{ itemID = 3820, quantity = 1 }, { itemID = 3821, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_93",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[11450] = {
    spellID      = 11450,
    name         = "Elixir of Greater Defense",
    requiredSkill = 195,
    resultItemID = 8951,
    recipeItemID = nil,
    materials    = {{ itemID = 3355, quantity = 1 }, { itemID = 3821, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_65",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[11451] = {
    spellID      = 11451,
    name         = "Oil of Immolation",
    requiredSkill = 205,
    resultItemID = 8956,
    recipeItemID = nil,
    materials    = {{ itemID = 4625, quantity = 1 }, { itemID = 3821, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_11",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[11452] = {
    spellID      = 11452,
    name         = "Restorative Potion",
    requiredSkill = 215,
    resultItemID = 9030,
    recipeItemID = nil,
    materials    = {{ itemID = 7067, quantity = 1 }, { itemID = 3821, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_01",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[11453] = {
    spellID      = 11453,
    name         = "Magic Resistance Potion",
    requiredSkill = 210,
    resultItemID = 9036,
    recipeItemID = 9293,
    materials    = {{ itemID = 3358, quantity = 1 }, { itemID = 8831, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = nil,
    recipeIconID = nil,
    source       = "vendor",
    sourceDetail = nil,
},

[11456] = {
    spellID      = 11456,
    name         = "Goblin Rocket Fuel",
    requiredSkill = 210,
    resultItemID = 9061,
    recipeItemID = nil,
    materials    = {{ itemID = 4625, quantity = 1 }, { itemID = 9260, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_cask_02",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[11457] = {
    spellID      = 11457,
    name         = "Superior Healing Potion",
    requiredSkill = 215,
    resultItemID = 3928,
    recipeItemID = nil,
    materials    = {{ itemID = 8838, quantity = 1 }, { itemID = 3358, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_53",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[11458] = {
    spellID      = 11458,
    name         = "Wildvine Potion",
    requiredSkill = 225,
    resultItemID = 9144,
    recipeItemID = 9294,
    materials    = {{ itemID = 8153, quantity = 1 }, { itemID = 8831, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_34",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[11459] = {
    spellID      = 11459,
    name         = "Philosopher's Stone",
    requiredSkill = 225,
    resultItemID = 9149,
    recipeItemID = 9303,
    materials    = {{ itemID = 3575, quantity = 4 }, { itemID = 9262, quantity = 1 }, { itemID = 8831, quantity = 4 }, { itemID = 4625, quantity = 4 }},
    resultIconID = "inv_misc_orb_01",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[11460] = {
    spellID      = 11460,
    name         = "Elixir of Detect Undead",
    requiredSkill = 230,
    resultItemID = 9154,
    recipeItemID = nil,
    materials    = {{ itemID = 8836, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_53",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[11461] = {
    spellID      = 11461,
    name         = "Arcane Elixir",
    requiredSkill = 235,
    resultItemID = 9155,
    recipeItemID = nil,
    materials    = {{ itemID = 8839, quantity = 1 }, { itemID = 3821, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_30",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[11464] = {
    spellID      = 11464,
    name         = "Invisibility Potion",
    requiredSkill = 235,
    resultItemID = 9172,
    recipeItemID = 9295,
    materials    = {{ itemID = 8845, quantity = 1 }, { itemID = 8838, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_25",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[11465] = {
    spellID      = 11465,
    name         = "Elixir of Greater Intellect",
    requiredSkill = 235,
    resultItemID = 9179,
    recipeItemID = nil,
    materials    = {{ itemID = 8839, quantity = 1 }, { itemID = 3358, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_10",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[11466] = {
    spellID      = 11466,
    name         = "Gift of Arthas",
    requiredSkill = 240,
    resultItemID = 9088,
    recipeItemID = 9296,
    materials    = {{ itemID = 8836, quantity = 1 }, { itemID = 8839, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_28",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[11467] = {
    spellID      = 11467,
    name         = "Elixir of Greater Agility",
    requiredSkill = 240,
    resultItemID = 9187,
    recipeItemID = nil,
    materials    = {{ itemID = 8838, quantity = 1 }, { itemID = 3821, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_94",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[11468] = {
    spellID      = 11468,
    name         = "Elixir of Dream Vision",
    requiredSkill = 240,
    resultItemID = 9197,
    recipeItemID = 9297,
    materials    = {{ itemID = 8831, quantity = 3 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_14",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[11472] = {
    spellID      = 11472,
    name         = "Elixir of Giants",
    requiredSkill = 245,
    resultItemID = 9206,
    recipeItemID = 9298,
    materials    = {{ itemID = 8838, quantity = 1 }, { itemID = 8846, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_61",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[11473] = {
    spellID      = 11473,
    name         = "Ghost Dye",
    requiredSkill = 245,
    resultItemID = 9210,
    recipeItemID = 9302,
    materials    = {{ itemID = 8845, quantity = 2 }, { itemID = 4342, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_poison_mindnumbing",
    recipeIconID = "inv_scroll_05",
    source       = "drop",
    sourceDetail = nil,
},

[11476] = {
    spellID      = 11476,
    name         = "Elixir of Shadow Power",
    requiredSkill = 250,
    resultItemID = 9264,
    recipeItemID = 9301,
    materials    = {{ itemID = 8845, quantity = 3 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_46",
    recipeIconID = "inv_scroll_06",
    source       = "drop",
    sourceDetail = nil,
},

[11477] = {
    spellID      = 11477,
    name         = "Elixir of Demonslaying",
    requiredSkill = 250,
    resultItemID = 9224,
    recipeItemID = 9300,
    materials    = {{ itemID = 8846, quantity = 1 }, { itemID = 8845, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_27",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[11478] = {
    spellID      = 11478,
    name         = "Elixir of Detect Demon",
    requiredSkill = 250,
    resultItemID = 9233,
    recipeItemID = nil,
    materials    = {{ itemID = 8846, quantity = 2 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_53",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[11479] = {
    spellID      = 11479,
    name         = "Transmute: Iron to Gold",
    requiredSkill = 225,
    resultItemID = 3577,
    recipeItemID = 9304,
    materials    = {{ itemID = 3575, quantity = 1 }},
    resultIconID = "inv_ingot_03",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[11480] = {
    spellID      = 11480,
    name         = "Transmute: Mithril to Truesilver",
    requiredSkill = 225,
    resultItemID = 6037,
    recipeItemID = 9305,
    materials    = {{ itemID = 3860, quantity = 1 }},
    resultIconID = "inv_ingot_08",
    recipeIconID = "inv_scroll_03",
    source       = "trainer",
    sourceDetail = {"Brek Stonehoof", "Brock Stoneseeker", "Brom Killian", "Dank Drizzlecut", "Gelman Stonehand", "Geofram Bouldertoe", "Johan Focht", "Krunn", "Kurdram Stonehammer", "Makaru", "Matt Johnson", "Pikkle", "Yarr Hammerstone"},
},

[11611] = {
    spellID      = 11611,
    name         = "Alchemy",
    requiredSkill = 200,
    resultItemID = nil,
    recipeItemID = nil,
    materials    = nil,
    resultIconID = nil,
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[12609] = {
    spellID      = 12609,
    name         = "Catseye Elixir",
    requiredSkill = 200,
    resultItemID = 10592,
    recipeItemID = nil,
    materials    = {{ itemID = 3821, quantity = 1 }, { itemID = 3818, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_36",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[15833] = {
    spellID      = 15833,
    name         = "Dreamless Sleep Potion",
    requiredSkill = 230,
    resultItemID = 12190,
    recipeItemID = nil,
    materials    = {{ itemID = 8831, quantity = 3 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_83",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[17187] = {
    spellID      = 17187,
    name         = "Transmute: Arcanite",
    requiredSkill = 275,
    resultItemID = 12360,
    recipeItemID = 12958,
    materials    = {{ itemID = 12359, quantity = 1 }, { itemID = 12363, quantity = 1 }},
    resultIconID = "inv_misc_stonetablet_05",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[17551] = {
    spellID      = 17551,
    name         = "Stonescale Oil",
    requiredSkill = 250,
    resultItemID = 13423,
    recipeItemID = nil,
    materials    = {{ itemID = 13422, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_68",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[17552] = {
    spellID      = 17552,
    name         = "Mighty Rage Potion",
    requiredSkill = 255,
    resultItemID = 13442,
    recipeItemID = 13476,
    materials    = {{ itemID = 8846, quantity = 3 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_41",
    recipeIconID = "inv_scroll_06",
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[17553] = {
    spellID      = 17553,
    name         = "Superior Mana Potion",
    requiredSkill = 260,
    resultItemID = 13443,
    recipeItemID = 13477,
    materials    = {{ itemID = 8838, quantity = 2 }, { itemID = 8839, quantity = 2 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_74",
    recipeIconID = "inv_scroll_03",
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[17554] = {
    spellID      = 17554,
    name         = "Elixir of Superior Defense",
    requiredSkill = 265,
    resultItemID = 13445,
    recipeItemID = 13478,
    materials    = {{ itemID = 13423, quantity = 2 }, { itemID = 8838, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_66",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[17555] = {
    spellID      = 17555,
    name         = "Elixir of the Sages",
    requiredSkill = 270,
    resultItemID = 13447,
    recipeItemID = 13479,
    materials    = {{ itemID = 13463, quantity = 1 }, { itemID = 13466, quantity = 2 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_29",
    recipeIconID = "inv_scroll_06",
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[17556] = {
    spellID      = 17556,
    name         = "Major Healing Potion",
    requiredSkill = 275,
    resultItemID = 13446,
    recipeItemID = 13480,
    materials    = {{ itemID = 13464, quantity = 2 }, { itemID = 13465, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_54",
    recipeIconID = "inv_scroll_03",
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[17557] = {
    spellID      = 17557,
    name         = "Elixir of Brute Force",
    requiredSkill = 275,
    resultItemID = 13453,
    recipeItemID = 13481,
    materials    = {{ itemID = 8846, quantity = 2 }, { itemID = 13466, quantity = 2 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_59",
    recipeIconID = "inv_scroll_06",
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[17559] = {
    spellID      = 17559,
    name         = "Transmute: Air to Fire",
    requiredSkill = 275,
    resultItemID = 7078,
    recipeItemID = 13482,
    materials    = {{ itemID = 7082, quantity = 1 }},
    resultIconID = "spell_fire_volcano",
    recipeIconID = "inv_scroll_06",
    source       = "drop",
    sourceDetail = nil,
},

[17560] = {
    spellID      = 17560,
    name         = "Transmute: Fire to Earth",
    requiredSkill = 275,
    resultItemID = 7076,
    recipeItemID = 13483,
    materials    = {{ itemID = 7078, quantity = 1 }},
    resultIconID = "spell_nature_strengthofearthtotem02",
    recipeIconID = "inv_scroll_06",
    source       = "drop",
    sourceDetail = nil,
},

[17561] = {
    spellID      = 17561,
    name         = "Transmute: Earth to Water",
    requiredSkill = 275,
    resultItemID = 7080,
    recipeItemID = 13484,
    materials    = {{ itemID = 7076, quantity = 1 }},
    resultIconID = "spell_nature_acid_01",
    recipeIconID = "inv_scroll_06",
    source       = "drop",
    sourceDetail = nil,
},

[17562] = {
    spellID      = 17562,
    name         = "Transmute: Water to Air",
    requiredSkill = 275,
    resultItemID = 7082,
    recipeItemID = 13485,
    materials    = {{ itemID = 7080, quantity = 1 }},
    resultIconID = "spell_nature_earthbind",
    recipeIconID = "inv_scroll_06",
    source       = "drop",
    sourceDetail = nil,
},

[17563] = {
    spellID      = 17563,
    name         = "Transmute: Undeath to Water",
    requiredSkill = 275,
    resultItemID = 7080,
    recipeItemID = 13486,
    materials    = {{ itemID = 12808, quantity = 1 }},
    resultIconID = "spell_nature_acid_01",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[17564] = {
    spellID      = 17564,
    name         = "Transmute: Water to Undeath",
    requiredSkill = 275,
    resultItemID = 12808,
    recipeItemID = 13487,
    materials    = {{ itemID = 7080, quantity = 1 }},
    resultIconID = "spell_shadow_shadetruesight",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[17565] = {
    spellID      = 17565,
    name         = "Transmute: Life to Earth",
    requiredSkill = 275,
    resultItemID = 7076,
    recipeItemID = 13488,
    materials    = {{ itemID = 12803, quantity = 1 }},
    resultIconID = "spell_nature_strengthofearthtotem02",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[17566] = {
    spellID      = 17566,
    name         = "Transmute: Earth to Life",
    requiredSkill = 275,
    resultItemID = 12803,
    recipeItemID = 13489,
    materials    = {{ itemID = 7076, quantity = 1 }},
    resultIconID = "spell_nature_abolishmagic",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[17570] = {
    spellID      = 17570,
    name         = "Greater Stoneshield Potion",
    requiredSkill = 280,
    resultItemID = 13455,
    recipeItemID = 13490,
    materials    = {{ itemID = 13423, quantity = 2 }, { itemID = 10620, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_69",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[17571] = {
    spellID      = 17571,
    name         = "Elixir of the Mongoose",
    requiredSkill = 280,
    resultItemID = 13452,
    recipeItemID = 13491,
    materials    = {{ itemID = 13465, quantity = 2 }, { itemID = 13466, quantity = 2 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_32",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[17572] = {
    spellID      = 17572,
    name         = "Purification Potion",
    requiredSkill = 285,
    resultItemID = 13462,
    recipeItemID = 13492,
    materials    = {{ itemID = 13467, quantity = 2 }, { itemID = 13466, quantity = 2 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_31",
    recipeIconID = "inv_scroll_06",
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[17573] = {
    spellID      = 17573,
    name         = "Greater Arcane Elixir",
    requiredSkill = 285,
    resultItemID = 13454,
    recipeItemID = 13493,
    materials    = {{ itemID = 13463, quantity = 3 }, { itemID = 13465, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_25",
    recipeIconID = "inv_scroll_06",
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[17574] = {
    spellID      = 17574,
    name         = "Greater Fire Protection Potion",
    requiredSkill = 290,
    resultItemID = 13457,
    recipeItemID = 13494,
    materials    = {{ itemID = 7068, quantity = 1 }, { itemID = 13463, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_24",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[17575] = {
    spellID      = 17575,
    name         = "Greater Frost Protection Potion",
    requiredSkill = 290,
    resultItemID = 13456,
    recipeItemID = 13495,
    materials    = {{ itemID = 7070, quantity = 1 }, { itemID = 13463, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_20",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[17576] = {
    spellID      = 17576,
    name         = "Greater Nature Protection Potion",
    requiredSkill = 290,
    resultItemID = 13458,
    recipeItemID = 13496,
    materials    = {{ itemID = 7067, quantity = 1 }, { itemID = 13463, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_22",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[17577] = {
    spellID      = 17577,
    name         = "Greater Arcane Protection Potion",
    requiredSkill = 290,
    resultItemID = 13461,
    recipeItemID = 13497,
    materials    = {{ itemID = 11176, quantity = 1 }, { itemID = 13463, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_83",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[17578] = {
    spellID      = 17578,
    name         = "Greater Shadow Protection Potion",
    requiredSkill = 290,
    resultItemID = 13459,
    recipeItemID = 13499,
    materials    = {{ itemID = 3824, quantity = 1 }, { itemID = 13463, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_23",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[17580] = {
    spellID      = 17580,
    name         = "Major Mana Potion",
    requiredSkill = 295,
    resultItemID = 13444,
    recipeItemID = 13501,
    materials    = {{ itemID = 13463, quantity = 3 }, { itemID = 13467, quantity = 2 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_76",
    recipeIconID = "inv_scroll_06",
    source       = "vendor_or_drop",
    sourceDetail = {"Magnus Frostwake"},
},

[17632] = {
    spellID      = 17632,
    name         = "Alchemist's Stone",
    requiredSkill = 300,
    resultItemID = 13503,
    recipeItemID = 13517,
    materials    = {{ itemID = 9149, quantity = 1 }, { itemID = 25867, quantity = 1 }, { itemID = 25868, quantity = 1 }, { itemID = 22794, quantity = 2 }, { itemID = 23571, quantity = 5 }},
    resultIconID = "spell_holy_pureofheart",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[17634] = {
    spellID      = 17634,
    name         = "Flask of Petrification",
    requiredSkill = 300,
    resultItemID = 13506,
    recipeItemID = 13518,
    materials    = {{ itemID = 13423, quantity = 7 }, { itemID = 13465, quantity = 3 }, { itemID = 13468, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_26",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[17635] = {
    spellID      = 17635,
    name         = "Flask of the Titans",
    requiredSkill = 300,
    resultItemID = 13510,
    recipeItemID = 13519,
    materials    = {{ itemID = 8846, quantity = 7 }, { itemID = 13423, quantity = 3 }, { itemID = 13468, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_62",
    recipeIconID = "inv_scroll_06",
    source       = "vendor_or_drop",
    sourceDetail = nil,
},

[17636] = {
    spellID      = 17636,
    name         = "Flask of Distilled Wisdom",
    requiredSkill = 300,
    resultItemID = 13511,
    recipeItemID = 13520,
    materials    = {{ itemID = 13463, quantity = 7 }, { itemID = 13467, quantity = 3 }, { itemID = 13468, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_97",
    recipeIconID = "inv_scroll_06",
    source       = "vendor_or_drop",
    sourceDetail = nil,
},

[17637] = {
    spellID      = 17637,
    name         = "Flask of Supreme Power",
    requiredSkill = 300,
    resultItemID = 13512,
    recipeItemID = 13521,
    materials    = {{ itemID = 13463, quantity = 7 }, { itemID = 13465, quantity = 3 }, { itemID = 13468, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_41",
    recipeIconID = "inv_scroll_06",
    source       = "vendor_or_drop",
    sourceDetail = nil,
},

[17638] = {
    spellID      = 17638,
    name         = "Flask of Chromatic Resistance",
    requiredSkill = 300,
    resultItemID = 13513,
    recipeItemID = 13522,
    materials    = {{ itemID = 13467, quantity = 7 }, { itemID = 13465, quantity = 3 }, { itemID = 13468, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = nil,
    recipeIconID = nil,
    source       = "vendor_or_drop",
    sourceDetail = nil,
},

[21923] = {
    spellID      = 21923,
    name         = "Elixir of Frost Power",
    requiredSkill = 190,
    resultItemID = 17708,
    recipeItemID = 17709,
    materials    = {{ itemID = 3819, quantity = 2 }, { itemID = 3358, quantity = 1 }, { itemID = 3372, quantity = 1 }},
    resultIconID = "inv_potion_03",
    recipeIconID = "inv_scroll_03",
    source       = "vendor",
    sourceDetail = nil,
},

[22732] = {
    spellID      = 22732,
    name         = "Major Rejuvenation Potion",
    requiredSkill = 300,
    resultItemID = 18253,
    recipeItemID = 18257,
    materials    = {{ itemID = 10286, quantity = 1 }, { itemID = 13464, quantity = 4 }, { itemID = 13463, quantity = 4 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_145",
    recipeIconID = "inv_scroll_05",
    source       = "vendor",
    sourceDetail = nil,
},

[22808] = {
    spellID      = 22808,
    name         = "Elixir of Greater Water Breathing",
    requiredSkill = 215,
    resultItemID = 18294,
    recipeItemID = nil,
    materials    = {{ itemID = 7972, quantity = 1 }, { itemID = 8831, quantity = 2 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_05",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Ainethil", "Alchemist Gribble", "Alchemist Mallory", "Alchemist Narett", "Apothecary Antonivich", "Arcanist Sheynathren", "Bena Winterhoof", "Camberon", "Carolai Anise", "Cyndra Kindwhisper", "Daedal", "Doctor Herbert Halsey", "Ghak Healtouch", "Jaxin Chong", "Kylanna", "Kylanna Windwhisper", "Lilyssia Nightbreeze", "Lorokeem", "Lucc", "Miao'zan", "Rogvar", "Serge Hinott", "Tally Berryfizz", "Yelmak"},
},

[24266] = {
    spellID      = 24266,
    name         = "Gurubashi Mojo Madness",
    requiredSkill = 315,
    resultItemID = 19931,
    recipeItemID = nil,
    materials    = {{ itemID = 12938, quantity = 1 }, { itemID = 19943, quantity = 1 }, { itemID = 12804, quantity = 6 }, { itemID = 13468, quantity = 1 }},
    resultIconID = "inv_poison_mindnumbing",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[24365] = {
    spellID      = 24365,
    name         = "Mageblood Potion",
    requiredSkill = 275,
    resultItemID = 20007,
    recipeItemID = 20011,
    materials    = {{ itemID = 13463, quantity = 1 }, { itemID = 13466, quantity = 2 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_45",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[24366] = {
    spellID      = 24366,
    name         = "Greater Dreamless Sleep Potion",
    requiredSkill = 275,
    resultItemID = 20002,
    recipeItemID = 20012,
    materials    = {{ itemID = 13463, quantity = 2 }, { itemID = 13464, quantity = 1 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_83",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[24367] = {
    spellID      = 24367,
    name         = "Living Action Potion",
    requiredSkill = 285,
    resultItemID = 20008,
    recipeItemID = 20013,
    materials    = {{ itemID = 13467, quantity = 2 }, { itemID = 13465, quantity = 2 }, { itemID = 10286, quantity = 2 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_07",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[24368] = {
    spellID      = 24368,
    name         = "Major Troll's Blood Potion",
    requiredSkill = 290,
    resultItemID = 20004,
    recipeItemID = 20014,
    materials    = {{ itemID = 8846, quantity = 1 }, { itemID = 13466, quantity = 2 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_80",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[25146] = {
    spellID      = 25146,
    name         = "Transmute: Elemental Fire",
    requiredSkill = 300,
    resultItemID = 7068,
    recipeItemID = 20761,
    materials    = {{ itemID = 7077, quantity = 1 }},
    resultIconID = "spell_fire_fire",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[26277] = {
    spellID      = 26277,
    name         = "Elixir of Greater Firepower",
    requiredSkill = 250,
    resultItemID = 21546,
    recipeItemID = 21547,
    materials    = {{ itemID = 6371, quantity = 3 }, { itemID = 4625, quantity = 3 }, { itemID = 8925, quantity = 1 }},
    resultIconID = "inv_potion_60",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[28543] = {
    spellID      = 28543,
    name         = "Elixir of Camouflage",
    requiredSkill = 305,
    resultItemID = 22823,
    recipeItemID = 22900,
    materials    = {{ itemID = 22787, quantity = 1 }, { itemID = 22785, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_150",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[28544] = {
    spellID      = 28544,
    name         = "Elixir of Major Strength",
    requiredSkill = 305,
    resultItemID = 22824,
    recipeItemID = nil,
    materials    = {{ itemID = 13465, quantity = 1 }, { itemID = 22785, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_147",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Alchemist Gribble", "Apothecary Antonivich", "Lorokeem"},
},

[28545] = {
    spellID      = 28545,
    name         = "Elixir of Healing Power",
    requiredSkill = 310,
    resultItemID = 22825,
    recipeItemID = nil,
    materials    = {{ itemID = 13464, quantity = 1 }, { itemID = 22786, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_142",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Alchemist Gribble", "Apothecary Antonivich", "Lorokeem"},
},

[28546] = {
    spellID      = 28546,
    name         = "Sneaking Potion",
    requiredSkill = 315,
    resultItemID = 22826,
    recipeItemID = 22901,
    materials    = {{ itemID = 22787, quantity = 2 }, { itemID = 22785, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_110",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[28549] = {
    spellID      = 28549,
    name         = "Elixir of Major Frost Power",
    requiredSkill = 320,
    resultItemID = 22827,
    recipeItemID = 22902,
    materials    = {{ itemID = 22578, quantity = 2 }, { itemID = 22790, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_148",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[28550] = {
    spellID      = 28550,
    name         = "Insane Strength Potion",
    requiredSkill = 320,
    resultItemID = 22828,
    recipeItemID = 22903,
    materials    = {{ itemID = 22789, quantity = 3 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_109",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[28551] = {
    spellID      = 28551,
    name         = "Super Healing Potion",
    requiredSkill = 325,
    resultItemID = 22829,
    recipeItemID = nil,
    materials    = {{ itemID = 22791, quantity = 2 }, { itemID = 22785, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_131",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Alchemist Gribble", "Apothecary Antonivich", "Lorokeem"},
},

[28552] = {
    spellID      = 28552,
    name         = "Elixir of the Searching Eye",
    requiredSkill = 325,
    resultItemID = 22830,
    recipeItemID = 22904,
    materials    = {{ itemID = 22787, quantity = 2 }, { itemID = 22789, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_135",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[28553] = {
    spellID      = 28553,
    name         = "Elixir of Major Agility",
    requiredSkill = 330,
    resultItemID = 22831,
    recipeItemID = 22905,
    materials    = {{ itemID = 22789, quantity = 1 }, { itemID = 22785, quantity = 2 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_127",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[28554] = {
    spellID      = 28554,
    name         = "Shrouding Potion",
    requiredSkill = 335,
    resultItemID = 22871,
    recipeItemID = 22906,
    materials    = {{ itemID = 22787, quantity = 3 }, { itemID = 22791, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_144",
    recipeIconID = "inv_scroll_06",
    source       = "drop",
    sourceDetail = nil,
},

[28555] = {
    spellID      = 28555,
    name         = "Super Mana Potion",
    requiredSkill = 340,
    resultItemID = 22832,
    recipeItemID = 22907,
    materials    = {{ itemID = 22786, quantity = 2 }, { itemID = 22785, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_137",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[28556] = {
    spellID      = 28556,
    name         = "Elixir of Major Firepower",
    requiredSkill = 345,
    resultItemID = 22833,
    recipeItemID = 22908,
    materials    = {{ itemID = 22574, quantity = 2 }, { itemID = 22790, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_146",
    recipeIconID = "inv_scroll_06",
    source       = "drop",
    sourceDetail = nil,
},

[28557] = {
    spellID      = 28557,
    name         = "Elixir of Major Defense",
    requiredSkill = 345,
    resultItemID = 22834,
    recipeItemID = 22909,
    materials    = {{ itemID = 22790, quantity = 3 }, { itemID = 22789, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_122",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[28558] = {
    spellID      = 28558,
    name         = "Elixir of Major Shadow Power",
    requiredSkill = 350,
    resultItemID = 22835,
    recipeItemID = 22910,
    materials    = {{ itemID = 22790, quantity = 1 }, { itemID = 22792, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_145",
    recipeIconID = "inv_scroll_06",
    source       = "drop",
    sourceDetail = nil,
},

[28562] = {
    spellID      = 28562,
    name         = "Major Dreamless Sleep Potion",
    requiredSkill = 350,
    resultItemID = 22836,
    recipeItemID = 22911,
    materials    = {{ itemID = 22786, quantity = 1 }, { itemID = 22792, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_139",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[28563] = {
    spellID      = 28563,
    name         = "Heroic Potion",
    requiredSkill = 350,
    resultItemID = 22837,
    recipeItemID = 22912,
    materials    = {{ itemID = 22789, quantity = 2 }, { itemID = 22790, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_106",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[28564] = {
    spellID      = 28564,
    name         = "Haste Potion",
    requiredSkill = 350,
    resultItemID = 22838,
    recipeItemID = 22913,
    materials    = {{ itemID = 22789, quantity = 2 }, { itemID = 22791, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_108",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[28565] = {
    spellID      = 28565,
    name         = "Destruction Potion",
    requiredSkill = 350,
    resultItemID = 22839,
    recipeItemID = 22914,
    materials    = {{ itemID = 22792, quantity = 2 }, { itemID = 22791, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_107",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[28566] = {
    spellID      = 28566,
    name         = "Transmute: Primal Air to Fire",
    requiredSkill = 350,
    resultItemID = 21884,
    recipeItemID = 22915,
    materials    = {{ itemID = 22451, quantity = 1 }},
    resultIconID = "inv_elemental_primal_fire",
    recipeIconID = "inv_scroll_06",
    source       = "drop",
    sourceDetail = nil,
},

[28567] = {
    spellID      = 28567,
    name         = "Transmute: Primal Earth to Water",
    requiredSkill = 350,
    resultItemID = 21885,
    recipeItemID = 22916,
    materials    = {{ itemID = 22452, quantity = 1 }},
    resultIconID = "inv_elemental_primal_water",
    recipeIconID = "inv_scroll_06",
    source       = "drop",
    sourceDetail = nil,
},

[28568] = {
    spellID      = 28568,
    name         = "Transmute: Primal Fire to Earth",
    requiredSkill = 350,
    resultItemID = 22452,
    recipeItemID = 22917,
    materials    = {{ itemID = 21884, quantity = 1 }},
    resultIconID = "inv_elemental_primal_earth",
    recipeIconID = "inv_scroll_06",
    source       = "drop",
    sourceDetail = nil,
},

[28569] = {
    spellID      = 28569,
    name         = "Transmute: Primal Water to Air",
    requiredSkill = 350,
    resultItemID = 22451,
    recipeItemID = 22918,
    materials    = {{ itemID = 21885, quantity = 1 }},
    resultIconID = "inv_elemental_primal_air",
    recipeIconID = "inv_scroll_06",
    source       = "drop",
    sourceDetail = nil,
},

[28570] = {
    spellID      = 28570,
    name         = "Elixir of Major Mageblood",
    requiredSkill = 355,
    resultItemID = 22840,
    recipeItemID = 22919,
    materials    = {{ itemID = 22790, quantity = 1 }, { itemID = 22791, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_151",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[28571] = {
    spellID      = 28571,
    name         = "Major Fire Protection Potion",
    requiredSkill = 360,
    resultItemID = 22841,
    recipeItemID = 22920,
    materials    = {{ itemID = 21884, quantity = 1 }, { itemID = 22793, quantity = 3 }, { itemID = 18256, quantity = 5 }},
    resultIconID = "inv_potion_124",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[28572] = {
    spellID      = 28572,
    name         = "Major Frost Protection Potion",
    requiredSkill = 360,
    resultItemID = 22842,
    recipeItemID = 22921,
    materials    = {{ itemID = 21885, quantity = 1 }, { itemID = 22793, quantity = 3 }, { itemID = 18256, quantity = 5 }},
    resultIconID = "inv_potion_126",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[28573] = {
    spellID      = 28573,
    name         = "Major Nature Protection Potion",
    requiredSkill = 360,
    resultItemID = 22844,
    recipeItemID = 22922,
    materials    = {{ itemID = 21886, quantity = 1 }, { itemID = 22793, quantity = 3 }, { itemID = 18256, quantity = 5 }},
    resultIconID = "inv_potion_127",
    recipeIconID = "inv_scroll_06",
    source       = "drop",
    sourceDetail = nil,
},

[28575] = {
    spellID      = 28575,
    name         = "Major Arcane Protection Potion",
    requiredSkill = 360,
    resultItemID = 22845,
    recipeItemID = 22923,
    materials    = {{ itemID = 22457, quantity = 1 }, { itemID = 22793, quantity = 3 }, { itemID = 18256, quantity = 5 }},
    resultIconID = "inv_potion_128",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[28576] = {
    spellID      = 28576,
    name         = "Major Shadow Protection Potion",
    requiredSkill = 360,
    resultItemID = 22846,
    recipeItemID = 22924,
    materials    = {{ itemID = 22456, quantity = 1 }, { itemID = 22793, quantity = 3 }, { itemID = 18256, quantity = 5 }},
    resultIconID = "inv_potion_123",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[28577] = {
    spellID      = 28577,
    name         = "Major Holy Protection Potion",
    requiredSkill = 360,
    resultItemID = 22847,
    recipeItemID = 22925,
    materials    = {{ itemID = 21886, quantity = 1 }, { itemID = 22793, quantity = 3 }, { itemID = 18256, quantity = 5 }},
    resultIconID = "inv_potion_125",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[28578] = {
    spellID      = 28578,
    name         = "Elixir of Empowerment",
    requiredSkill = 365,
    resultItemID = 22848,
    recipeItemID = 22926,
    materials    = {{ itemID = 22791, quantity = 1 }, { itemID = 22793, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_136",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[28579] = {
    spellID      = 28579,
    name         = "Ironshield Potion",
    requiredSkill = 365,
    resultItemID = 22849,
    recipeItemID = 22927,
    materials    = {{ itemID = 22790, quantity = 2 }, { itemID = 22573, quantity = 3 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_133",
    recipeIconID = "inv_scroll_06",
    source       = "vendor",
    sourceDetail = nil,
},

[28580] = {
    spellID      = 28580,
    name         = "Transmute: Primal Shadow to Water",
    requiredSkill = 385,
    resultItemID = 21885,
    recipeItemID = nil,
    materials    = {{ itemID = 22456, quantity = 1 }},
    resultIconID = "inv_elemental_primal_water",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[28581] = {
    spellID      = 28581,
    name         = "Transmute: Primal Water to Shadow",
    requiredSkill = 385,
    resultItemID = 22456,
    recipeItemID = nil,
    materials    = {{ itemID = 21885, quantity = 1 }},
    resultIconID = "inv_elemental_primal_shadow",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[28582] = {
    spellID      = 28582,
    name         = "Transmute: Primal Mana to Fire",
    requiredSkill = 385,
    resultItemID = 21884,
    recipeItemID = nil,
    materials    = {{ itemID = 22457, quantity = 1 }},
    resultIconID = "inv_elemental_primal_fire",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[28583] = {
    spellID      = 28583,
    name         = "Transmute: Primal Fire to Mana",
    requiredSkill = 385,
    resultItemID = 22457,
    recipeItemID = nil,
    materials    = {{ itemID = 21884, quantity = 1 }},
    resultIconID = "inv_elemental_primal_mana",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[28584] = {
    spellID      = 28584,
    name         = "Transmute: Primal Life to Earth",
    requiredSkill = 385,
    resultItemID = 22452,
    recipeItemID = nil,
    materials    = {{ itemID = 21886, quantity = 1 }},
    resultIconID = "inv_elemental_primal_earth",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[28585] = {
    spellID      = 28585,
    name         = "Transmute: Primal Earth to Life",
    requiredSkill = 385,
    resultItemID = 21886,
    recipeItemID = nil,
    materials    = {{ itemID = 22452, quantity = 1 }},
    resultIconID = "inv_elemental_primal_life",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[28586] = {
    spellID      = 28586,
    name         = "Super Rejuvenation Potion",
    requiredSkill = 390,
    resultItemID = 22850,
    recipeItemID = nil,
    materials    = {{ itemID = 22793, quantity = 2 }, { itemID = 22786, quantity = 1 }, { itemID = 22791, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_134",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[28587] = {
    spellID      = 28587,
    name         = "Flask of Fortification",
    requiredSkill = 390,
    resultItemID = 22851,
    recipeItemID = nil,
    materials    = {{ itemID = 22794, quantity = 1 }, { itemID = 22793, quantity = 3 }, { itemID = 22790, quantity = 7 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_119",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[28588] = {
    spellID      = 28588,
    name         = "Flask of Mighty Restoration",
    requiredSkill = 390,
    resultItemID = 22853,
    recipeItemID = nil,
    materials    = {{ itemID = 22794, quantity = 1 }, { itemID = 22793, quantity = 3 }, { itemID = 22786, quantity = 7 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_118",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[28589] = {
    spellID      = 28589,
    name         = "Flask of Relentless Assault",
    requiredSkill = 390,
    resultItemID = 22854,
    recipeItemID = nil,
    materials    = {{ itemID = 22794, quantity = 1 }, { itemID = 22793, quantity = 3 }, { itemID = 22789, quantity = 7 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_117",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[28590] = {
    spellID      = 28590,
    name         = "Flask of Blinding Light",
    requiredSkill = 390,
    resultItemID = 22861,
    recipeItemID = nil,
    materials    = {{ itemID = 22794, quantity = 1 }, { itemID = 22793, quantity = 3 }, { itemID = 22791, quantity = 7 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_116",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[28591] = {
    spellID      = 28591,
    name         = "Flask of Pure Death",
    requiredSkill = 390,
    resultItemID = 22866,
    recipeItemID = nil,
    materials    = {{ itemID = 22794, quantity = 1 }, { itemID = 22793, quantity = 3 }, { itemID = 22792, quantity = 7 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_115",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[28596] = {
    spellID      = 28596,
    name         = "Alchemy",
    requiredSkill = 275,
    resultItemID = nil,
    recipeItemID = nil,
    materials    = nil,
    resultIconID = nil,
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Alchemist Gribble", "Apothecary Antonivich", "Lorokeem"},
},

[28672] = {
    spellID      = 28672,
    name         = "Transmutation Master",
    requiredSkill = 9999,
    resultItemID = nil,
    recipeItemID = nil,
    materials    = nil,
    resultIconID = nil,
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[28675] = {
    spellID      = 28675,
    name         = "Potion Master",
    requiredSkill = 9999,
    resultItemID = nil,
    recipeItemID = nil,
    materials    = nil,
    resultIconID = nil,
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[28677] = {
    spellID      = 28677,
    name         = "Elixir Master",
    requiredSkill = 9999,
    resultItemID = nil,
    recipeItemID = nil,
    materials    = nil,
    resultIconID = nil,
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[29688] = {
    spellID      = 29688,
    name         = "Transmute: Primal Might",
    requiredSkill = 350,
    resultItemID = 23571,
    recipeItemID = 23574,
    materials    = {{ itemID = 22452, quantity = 1 }, { itemID = 21885, quantity = 1 }, { itemID = 22451, quantity = 1 }, { itemID = 21884, quantity = 1 }, { itemID = 22457, quantity = 1 }},
    resultIconID = "spell_nature_lightningoverload",
    recipeIconID = "inv_scroll_06",
    source       = "drop",
    sourceDetail = nil,
},

[32765] = {
    spellID      = 32765,
    name         = "Transmute: Earthstorm Diamond",
    requiredSkill = 350,
    resultItemID = 25867,
    recipeItemID = 25869,
    materials    = {{ itemID = 23079, quantity = 3 }, { itemID = 23107, quantity = 3 }, { itemID = 23112, quantity = 3 }, { itemID = 22452, quantity = 2 }, { itemID = 21885, quantity = 2 }},
    resultIconID = "inv_misc_gem_diamond_04",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[32766] = {
    spellID      = 32766,
    name         = "Transmute: Skyfire Diamond",
    requiredSkill = 350,
    resultItemID = 25868,
    recipeItemID = 25870,
    materials    = {{ itemID = 23077, quantity = 3 }, { itemID = 21929, quantity = 3 }, { itemID = 23117, quantity = 3 }, { itemID = 21884, quantity = 2 }, { itemID = 22451, quantity = 2 }},
    resultIconID = "inv_misc_gem_diamond_05",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[33732] = {
    spellID      = 33732,
    name         = "Volatile Healing Potion",
    requiredSkill = 300,
    resultItemID = 28100,
    recipeItemID = nil,
    materials    = {{ itemID = 13464, quantity = 1 }, { itemID = 22785, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_40",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Alchemist Gribble", "Apothecary Antonivich", "Lorokeem"},
},

[33733] = {
    spellID      = 33733,
    name         = "Unstable Mana Potion",
    requiredSkill = 310,
    resultItemID = 28101,
    recipeItemID = nil,
    materials    = {{ itemID = 22787, quantity = 2 }, { itemID = 22785, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_75",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Alchemist Gribble", "Apothecary Antonivich", "Lorokeem"},
},

[33738] = {
    spellID      = 33738,
    name         = "Onslaught Elixir",
    requiredSkill = 300,
    resultItemID = 28102,
    recipeItemID = nil,
    materials    = {{ itemID = 13465, quantity = 1 }, { itemID = 22785, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_58",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Alchemist Gribble", "Apothecary Antonivich", "Lorokeem"},
},

[33740] = {
    spellID      = 33740,
    name         = "Adept's Elixir",
    requiredSkill = 300,
    resultItemID = 28103,
    recipeItemID = nil,
    materials    = {{ itemID = 13463, quantity = 1 }, { itemID = 22785, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_96",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Alchemist Gribble", "Apothecary Antonivich", "Lorokeem"},
},

[33741] = {
    spellID      = 33741,
    name         = "Elixir of Mastery",
    requiredSkill = 315,
    resultItemID = 28104,
    recipeItemID = nil,
    materials    = {{ itemID = 22789, quantity = 3 }, { itemID = 22785, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_111",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Alchemist Gribble", "Apothecary Antonivich", "Lorokeem"},
},

[38070] = {
    spellID      = 38070,
    name         = "Mercurial Stone",
    requiredSkill = 325,
    resultItemID = 31080,
    recipeItemID = nil,
    materials    = {{ itemID = 22452, quantity = 1 }, { itemID = 21886, quantity = 1 }, { itemID = 22457, quantity = 1 }},
    resultIconID = "inv_misc_gem_lionseye_01",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Alchemist Gribble", "Apothecary Antonivich", "Lorokeem"},
},

[38960] = {
    spellID      = 38960,
    name         = "Fel Strength Elixir",
    requiredSkill = 335,
    resultItemID = 31679,
    recipeItemID = 31680,
    materials    = {{ itemID = 22789, quantity = 1 }, { itemID = 22792, quantity = 2 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_152",
    recipeIconID = "inv_scroll_05",
    source       = "vendor",
    sourceDetail = nil,
},

[38961] = {
    spellID      = 38961,
    name         = "Fel Mana Potion",
    requiredSkill = 360,
    resultItemID = 31677,
    recipeItemID = 31682,
    materials    = {{ itemID = 22793, quantity = 1 }, { itemID = 22792, quantity = 2 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_138",
    recipeIconID = "inv_scroll_05",
    source       = "vendor",
    sourceDetail = nil,
},

[38962] = {
    spellID      = 38962,
    name         = "Fel Regeneration Potion",
    requiredSkill = 345,
    resultItemID = 31676,
    recipeItemID = 31681,
    materials    = {{ itemID = 22785, quantity = 2 }, { itemID = 22792, quantity = 3 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_140",
    recipeIconID = "inv_scroll_05",
    source       = "vendor",
    sourceDetail = nil,
},

[39636] = {
    spellID      = 39636,
    name         = "Elixir of Major Fortitude",
    requiredSkill = 310,
    resultItemID = 32062,
    recipeItemID = nil,
    materials    = {{ itemID = 22787, quantity = 2 }, { itemID = 22785, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_158",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Alchemist Gribble", "Apothecary Antonivich", "Lorokeem"},
},

[39637] = {
    spellID      = 39637,
    name         = "Earthen Elixir",
    requiredSkill = 320,
    resultItemID = 32063,
    recipeItemID = 32070,
    materials    = {{ itemID = 22786, quantity = 1 }, { itemID = 22787, quantity = 2 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_154",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[39638] = {
    spellID      = 39638,
    name         = "Elixir of Draenic Wisdom",
    requiredSkill = 320,
    resultItemID = 32067,
    recipeItemID = nil,
    materials    = {{ itemID = 22785, quantity = 1 }, { itemID = 22789, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_155",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Alchemist Gribble", "Apothecary Antonivich", "Lorokeem"},
},

[39639] = {
    spellID      = 39639,
    name         = "Elixir of Ironskin",
    requiredSkill = 330,
    resultItemID = 32068,
    recipeItemID = 32071,
    materials    = {{ itemID = 22790, quantity = 1 }, { itemID = 22787, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = "inv_potion_159",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[41458] = {
    spellID      = 41458,
    name         = "Cauldron of Major Arcane Protection",
    requiredSkill = 360,
    resultItemID = 32839,
    recipeItemID = nil,
    materials    = {{ itemID = 22457, quantity = 2 }, { itemID = 22793, quantity = 7 }, { itemID = 23782, quantity = 1 }},
    resultIconID = "inv_misc_cauldron_arcane",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[41500] = {
    spellID      = 41500,
    name         = "Cauldron of Major Fire Protection",
    requiredSkill = 360,
    resultItemID = 32849,
    recipeItemID = nil,
    materials    = {{ itemID = 21884, quantity = 2 }, { itemID = 22793, quantity = 7 }, { itemID = 23782, quantity = 1 }},
    resultIconID = "inv_misc_cauldron_fire",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[41501] = {
    spellID      = 41501,
    name         = "Cauldron of Major Frost Protection",
    requiredSkill = 360,
    resultItemID = 32850,
    recipeItemID = nil,
    materials    = {{ itemID = 21885, quantity = 2 }, { itemID = 22793, quantity = 7 }, { itemID = 23782, quantity = 1 }},
    resultIconID = "inv_misc_cauldron_frost",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[41502] = {
    spellID      = 41502,
    name         = "Cauldron of Major Nature Protection",
    requiredSkill = 360,
    resultItemID = 32851,
    recipeItemID = nil,
    materials    = {{ itemID = 21886, quantity = 2 }, { itemID = 22793, quantity = 7 }, { itemID = 23782, quantity = 1 }},
    resultIconID = "inv_misc_cauldron_nature",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[41503] = {
    spellID      = 41503,
    name         = "Cauldron of Major Shadow Protection",
    requiredSkill = 360,
    resultItemID = 32852,
    recipeItemID = nil,
    materials    = {{ itemID = 22456, quantity = 2 }, { itemID = 22793, quantity = 7 }, { itemID = 23782, quantity = 1 }},
    resultIconID = "inv_misc_cauldron_shadow",
    recipeIconID = nil,
    source       = nil,
    sourceDetail = nil,
},

[42736] = {
    spellID      = 42736,
    name         = "Flask of Chromatic Wonder",
    requiredSkill = 375,
    resultItemID = 33208,
    recipeItemID = 33209,
    materials    = {{ itemID = 22786, quantity = 7 }, { itemID = 22791, quantity = 3 }, { itemID = 22794, quantity = 1 }, { itemID = 18256, quantity = 1 }},
    resultIconID = nil,
    recipeIconID = nil,
    source       = "drop",
    sourceDetail = nil,
},

[45061] = {
    spellID      = 45061,
    name         = "Mad Alchemist's Potion",
    requiredSkill = 325,
    resultItemID = 34440,
    recipeItemID = nil,
    materials    = {{ itemID = 8925, quantity = 1 }, { itemID = 22787, quantity = 2 }},
    resultIconID = "inv_potion_28",
    recipeIconID = nil,
    source       = "trainer",
    sourceDetail = {"Alchemist Gribble", "Apothecary Antonivich", "Lorokeem"},
},

[47046] = {
    spellID      = 47046,
    name         = "Guardian's Alchemist Stone",
    requiredSkill = 375,
    resultItemID = 35748,
    recipeItemID = 35752,
    materials    = {{ itemID = 13503, quantity = 1 }, { itemID = 22451, quantity = 6 }, { itemID = 30183, quantity = 2 }},
    resultIconID = "spell_nature_healingway",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[47048] = {
    spellID      = 47048,
    name         = "Sorcerer's Alchemist Stone",
    requiredSkill = 375,
    resultItemID = 35749,
    recipeItemID = 35753,
    materials    = {{ itemID = 13503, quantity = 1 }, { itemID = 21884, quantity = 6 }, { itemID = 30183, quantity = 2 }},
    resultIconID = "spell_nature_healingway",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[47049] = {
    spellID      = 47049,
    name         = "Redeemer's Alchemist Stone",
    requiredSkill = 375,
    resultItemID = 35750,
    recipeItemID = 35754,
    materials    = {{ itemID = 13503, quantity = 1 }, { itemID = 21886, quantity = 6 }, { itemID = 30183, quantity = 2 }},
    resultIconID = "spell_nature_healingway",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

[47050] = {
    spellID      = 47050,
    name         = "Assassin's Alchemist Stone",
    requiredSkill = 375,
    resultItemID = 35751,
    recipeItemID = 35755,
    materials    = {{ itemID = 13503, quantity = 1 }, { itemID = 22456, quantity = 6 }, { itemID = 30183, quantity = 2 }},
    resultIconID = "spell_nature_healingway",
    recipeIconID = "inv_scroll_03",
    source       = "drop",
    sourceDetail = nil,
},

}
